/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ps.customer.event.avro;
@org.apache.avro.specific.AvroGenerated
public enum CustomerType implements org.apache.avro.generic.GenericEnumSymbol<CustomerType> {
  PF, PJ, UNRECOGNIZED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CustomerType\",\"namespace\":\"ps.customer.event.avro\",\"symbols\":[\"PF\",\"PJ\",\"UNRECOGNIZED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
