/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ps.customer.event.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Options extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7933122876662481459L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Options\",\"namespace\":\"ps.customer.event.avro\",\"fields\":[{\"name\":\"enableNewsletter\",\"type\":\"boolean\",\"default\":false},{\"name\":\"contractAccepted\",\"type\":\"boolean\",\"default\":false}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Options> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Options> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Options> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Options> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Options> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Options to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Options from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Options instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Options fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private boolean enableNewsletter;
  private boolean contractAccepted;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Options() {}

  /**
   * All-args constructor.
   * @param enableNewsletter The new value for enableNewsletter
   * @param contractAccepted The new value for contractAccepted
   */
  public Options(java.lang.Boolean enableNewsletter, java.lang.Boolean contractAccepted) {
    this.enableNewsletter = enableNewsletter;
    this.contractAccepted = contractAccepted;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return enableNewsletter;
    case 1: return contractAccepted;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: enableNewsletter = (java.lang.Boolean)value$; break;
    case 1: contractAccepted = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'enableNewsletter' field.
   * @return The value of the 'enableNewsletter' field.
   */
  public boolean getEnableNewsletter() {
    return enableNewsletter;
  }


  /**
   * Sets the value of the 'enableNewsletter' field.
   * @param value the value to set.
   */
  public void setEnableNewsletter(boolean value) {
    this.enableNewsletter = value;
  }

  /**
   * Gets the value of the 'contractAccepted' field.
   * @return The value of the 'contractAccepted' field.
   */
  public boolean getContractAccepted() {
    return contractAccepted;
  }


  /**
   * Sets the value of the 'contractAccepted' field.
   * @param value the value to set.
   */
  public void setContractAccepted(boolean value) {
    this.contractAccepted = value;
  }

  /**
   * Creates a new Options RecordBuilder.
   * @return A new Options RecordBuilder
   */
  public static ps.customer.event.avro.Options.Builder newBuilder() {
    return new ps.customer.event.avro.Options.Builder();
  }

  /**
   * Creates a new Options RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Options RecordBuilder
   */
  public static ps.customer.event.avro.Options.Builder newBuilder(ps.customer.event.avro.Options.Builder other) {
    if (other == null) {
      return new ps.customer.event.avro.Options.Builder();
    } else {
      return new ps.customer.event.avro.Options.Builder(other);
    }
  }

  /**
   * Creates a new Options RecordBuilder by copying an existing Options instance.
   * @param other The existing instance to copy.
   * @return A new Options RecordBuilder
   */
  public static ps.customer.event.avro.Options.Builder newBuilder(ps.customer.event.avro.Options other) {
    if (other == null) {
      return new ps.customer.event.avro.Options.Builder();
    } else {
      return new ps.customer.event.avro.Options.Builder(other);
    }
  }

  /**
   * RecordBuilder for Options instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Options>
    implements org.apache.avro.data.RecordBuilder<Options> {

    private boolean enableNewsletter;
    private boolean contractAccepted;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ps.customer.event.avro.Options.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.enableNewsletter)) {
        this.enableNewsletter = data().deepCopy(fields()[0].schema(), other.enableNewsletter);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.contractAccepted)) {
        this.contractAccepted = data().deepCopy(fields()[1].schema(), other.contractAccepted);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Options instance
     * @param other The existing instance to copy.
     */
    private Builder(ps.customer.event.avro.Options other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.enableNewsletter)) {
        this.enableNewsletter = data().deepCopy(fields()[0].schema(), other.enableNewsletter);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contractAccepted)) {
        this.contractAccepted = data().deepCopy(fields()[1].schema(), other.contractAccepted);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'enableNewsletter' field.
      * @return The value.
      */
    public boolean getEnableNewsletter() {
      return enableNewsletter;
    }


    /**
      * Sets the value of the 'enableNewsletter' field.
      * @param value The value of 'enableNewsletter'.
      * @return This builder.
      */
    public ps.customer.event.avro.Options.Builder setEnableNewsletter(boolean value) {
      validate(fields()[0], value);
      this.enableNewsletter = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'enableNewsletter' field has been set.
      * @return True if the 'enableNewsletter' field has been set, false otherwise.
      */
    public boolean hasEnableNewsletter() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'enableNewsletter' field.
      * @return This builder.
      */
    public ps.customer.event.avro.Options.Builder clearEnableNewsletter() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'contractAccepted' field.
      * @return The value.
      */
    public boolean getContractAccepted() {
      return contractAccepted;
    }


    /**
      * Sets the value of the 'contractAccepted' field.
      * @param value The value of 'contractAccepted'.
      * @return This builder.
      */
    public ps.customer.event.avro.Options.Builder setContractAccepted(boolean value) {
      validate(fields()[1], value);
      this.contractAccepted = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'contractAccepted' field has been set.
      * @return True if the 'contractAccepted' field has been set, false otherwise.
      */
    public boolean hasContractAccepted() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'contractAccepted' field.
      * @return This builder.
      */
    public ps.customer.event.avro.Options.Builder clearContractAccepted() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Options build() {
      try {
        Options record = new Options();
        record.enableNewsletter = fieldSetFlags()[0] ? this.enableNewsletter : (java.lang.Boolean) defaultValue(fields()[0]);
        record.contractAccepted = fieldSetFlags()[1] ? this.contractAccepted : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Options>
    WRITER$ = (org.apache.avro.io.DatumWriter<Options>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Options>
    READER$ = (org.apache.avro.io.DatumReader<Options>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeBoolean(this.enableNewsletter);

    out.writeBoolean(this.contractAccepted);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.enableNewsletter = in.readBoolean();

      this.contractAccepted = in.readBoolean();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.enableNewsletter = in.readBoolean();
          break;

        case 1:
          this.contractAccepted = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










