/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ps.customer.event.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RegistryInformation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1732663085774487098L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RegistryInformation\",\"namespace\":\"ps.customer.event.avro\",\"fields\":[{\"name\":\"rg\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"issuingOranization\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"issuingDate\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"logicalType\":\"timestamp-micros\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RegistryInformation> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RegistryInformation> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RegistryInformation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RegistryInformation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RegistryInformation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RegistryInformation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RegistryInformation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RegistryInformation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RegistryInformation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence rg;
  private java.lang.CharSequence issuingOranization;
  private java.lang.CharSequence issuingDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RegistryInformation() {}

  /**
   * All-args constructor.
   * @param rg The new value for rg
   * @param issuingOranization The new value for issuingOranization
   * @param issuingDate The new value for issuingDate
   */
  public RegistryInformation(java.lang.CharSequence rg, java.lang.CharSequence issuingOranization, java.lang.CharSequence issuingDate) {
    this.rg = rg;
    this.issuingOranization = issuingOranization;
    this.issuingDate = issuingDate;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return rg;
    case 1: return issuingOranization;
    case 2: return issuingDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: rg = (java.lang.CharSequence)value$; break;
    case 1: issuingOranization = (java.lang.CharSequence)value$; break;
    case 2: issuingDate = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'rg' field.
   * @return The value of the 'rg' field.
   */
  public java.lang.CharSequence getRg() {
    return rg;
  }


  /**
   * Sets the value of the 'rg' field.
   * @param value the value to set.
   */
  public void setRg(java.lang.CharSequence value) {
    this.rg = value;
  }

  /**
   * Gets the value of the 'issuingOranization' field.
   * @return The value of the 'issuingOranization' field.
   */
  public java.lang.CharSequence getIssuingOranization() {
    return issuingOranization;
  }


  /**
   * Sets the value of the 'issuingOranization' field.
   * @param value the value to set.
   */
  public void setIssuingOranization(java.lang.CharSequence value) {
    this.issuingOranization = value;
  }

  /**
   * Gets the value of the 'issuingDate' field.
   * @return The value of the 'issuingDate' field.
   */
  public java.lang.CharSequence getIssuingDate() {
    return issuingDate;
  }


  /**
   * Sets the value of the 'issuingDate' field.
   * @param value the value to set.
   */
  public void setIssuingDate(java.lang.CharSequence value) {
    this.issuingDate = value;
  }

  /**
   * Creates a new RegistryInformation RecordBuilder.
   * @return A new RegistryInformation RecordBuilder
   */
  public static ps.customer.event.avro.RegistryInformation.Builder newBuilder() {
    return new ps.customer.event.avro.RegistryInformation.Builder();
  }

  /**
   * Creates a new RegistryInformation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RegistryInformation RecordBuilder
   */
  public static ps.customer.event.avro.RegistryInformation.Builder newBuilder(ps.customer.event.avro.RegistryInformation.Builder other) {
    if (other == null) {
      return new ps.customer.event.avro.RegistryInformation.Builder();
    } else {
      return new ps.customer.event.avro.RegistryInformation.Builder(other);
    }
  }

  /**
   * Creates a new RegistryInformation RecordBuilder by copying an existing RegistryInformation instance.
   * @param other The existing instance to copy.
   * @return A new RegistryInformation RecordBuilder
   */
  public static ps.customer.event.avro.RegistryInformation.Builder newBuilder(ps.customer.event.avro.RegistryInformation other) {
    if (other == null) {
      return new ps.customer.event.avro.RegistryInformation.Builder();
    } else {
      return new ps.customer.event.avro.RegistryInformation.Builder(other);
    }
  }

  /**
   * RecordBuilder for RegistryInformation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RegistryInformation>
    implements org.apache.avro.data.RecordBuilder<RegistryInformation> {

    private java.lang.CharSequence rg;
    private java.lang.CharSequence issuingOranization;
    private java.lang.CharSequence issuingDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ps.customer.event.avro.RegistryInformation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rg)) {
        this.rg = data().deepCopy(fields()[0].schema(), other.rg);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.issuingOranization)) {
        this.issuingOranization = data().deepCopy(fields()[1].schema(), other.issuingOranization);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.issuingDate)) {
        this.issuingDate = data().deepCopy(fields()[2].schema(), other.issuingDate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing RegistryInformation instance
     * @param other The existing instance to copy.
     */
    private Builder(ps.customer.event.avro.RegistryInformation other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.rg)) {
        this.rg = data().deepCopy(fields()[0].schema(), other.rg);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.issuingOranization)) {
        this.issuingOranization = data().deepCopy(fields()[1].schema(), other.issuingOranization);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.issuingDate)) {
        this.issuingDate = data().deepCopy(fields()[2].schema(), other.issuingDate);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'rg' field.
      * @return The value.
      */
    public java.lang.CharSequence getRg() {
      return rg;
    }


    /**
      * Sets the value of the 'rg' field.
      * @param value The value of 'rg'.
      * @return This builder.
      */
    public ps.customer.event.avro.RegistryInformation.Builder setRg(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.rg = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'rg' field has been set.
      * @return True if the 'rg' field has been set, false otherwise.
      */
    public boolean hasRg() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'rg' field.
      * @return This builder.
      */
    public ps.customer.event.avro.RegistryInformation.Builder clearRg() {
      rg = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'issuingOranization' field.
      * @return The value.
      */
    public java.lang.CharSequence getIssuingOranization() {
      return issuingOranization;
    }


    /**
      * Sets the value of the 'issuingOranization' field.
      * @param value The value of 'issuingOranization'.
      * @return This builder.
      */
    public ps.customer.event.avro.RegistryInformation.Builder setIssuingOranization(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.issuingOranization = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'issuingOranization' field has been set.
      * @return True if the 'issuingOranization' field has been set, false otherwise.
      */
    public boolean hasIssuingOranization() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'issuingOranization' field.
      * @return This builder.
      */
    public ps.customer.event.avro.RegistryInformation.Builder clearIssuingOranization() {
      issuingOranization = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'issuingDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getIssuingDate() {
      return issuingDate;
    }


    /**
      * Sets the value of the 'issuingDate' field.
      * @param value The value of 'issuingDate'.
      * @return This builder.
      */
    public ps.customer.event.avro.RegistryInformation.Builder setIssuingDate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.issuingDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'issuingDate' field has been set.
      * @return True if the 'issuingDate' field has been set, false otherwise.
      */
    public boolean hasIssuingDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'issuingDate' field.
      * @return This builder.
      */
    public ps.customer.event.avro.RegistryInformation.Builder clearIssuingDate() {
      issuingDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RegistryInformation build() {
      try {
        RegistryInformation record = new RegistryInformation();
        record.rg = fieldSetFlags()[0] ? this.rg : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.issuingOranization = fieldSetFlags()[1] ? this.issuingOranization : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.issuingDate = fieldSetFlags()[2] ? this.issuingDate : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RegistryInformation>
    WRITER$ = (org.apache.avro.io.DatumWriter<RegistryInformation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RegistryInformation>
    READER$ = (org.apache.avro.io.DatumReader<RegistryInformation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.rg == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.rg);
    }

    if (this.issuingOranization == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.issuingOranization);
    }

    if (this.issuingDate == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.issuingDate);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.rg = null;
      } else {
        this.rg = in.readString(this.rg instanceof Utf8 ? (Utf8)this.rg : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.issuingOranization = null;
      } else {
        this.issuingOranization = in.readString(this.issuingOranization instanceof Utf8 ? (Utf8)this.issuingOranization : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.issuingDate = null;
      } else {
        this.issuingDate = in.readString(this.issuingDate instanceof Utf8 ? (Utf8)this.issuingDate : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.rg = null;
          } else {
            this.rg = in.readString(this.rg instanceof Utf8 ? (Utf8)this.rg : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.issuingOranization = null;
          } else {
            this.issuingOranization = in.readString(this.issuingOranization instanceof Utf8 ? (Utf8)this.issuingOranization : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.issuingDate = null;
          } else {
            this.issuingDate = in.readString(this.issuingDate instanceof Utf8 ? (Utf8)this.issuingDate : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










